payment-mode:
  mappings:
    - id: "GSMA"
      type: "PAYMENT"
      endpoint: "/channel/gsma/transfer"
    - id: "MOJALOOP"
      type: "PAYMENT"
      endpoint: "/channel/transfer"
    - id: "SLCB"
      type: "BULK"
      endpoint: "bulk_connector_{MODE}-{dfspid}"
    - id: "CLOSEDLOOP"
      type: "BULK"
      endpoint: "bulk_connector_{MODE}-{dfspid}"
      debulkingDfspid: "lion"