version: 2.1
jobs:
  build_and_push:
    docker:
      - image: circleci/openjdk:17-buster-node-browsers-legacy
      
    environment:
      JVM_OPTS: -Xmx512m
      TERM: dumb
      # Add any environment variables needed for the build here
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.14

      # Login to DockerHub
      - run:
          name: Login to DockerHub
          command:  docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD 

      # Build the Docker image
      - run:
          name: Build Docker image
          command: |
            ./gradlew build
            docker build -t ph-ee-bulk-processor:latest .

      # Push the Docker image to DockerHub
      - run:
          name: Push Docker image to DockerHub
          command: |
            docker push somanath21/ph-ee-bulk-processor:latest

workflows:
  version: 2
  build_and_push:
    jobs:
      - build_and_push:
          context:
            - DOCKER