version: 2.1
jobs:
  build_push_tag_image:
    docker:
      - image: circleci/openjdk:17-buster-node-browsers-legacy
    environment:
      JVM_OPTS: -Xmx512m
      TERM: dumb

    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.14

      # # Install Docker CLI
      # - run:
      #     name: Install Docker CLI
      #     command: |
      #       curl -fsSL https://get.docker.com -o get-docker.sh
      #       sudo sh get-docker.sh

      # Build and push Docker image on tag release
      - run:
          name: Build and Push Docker image
          command: |
            if [ "${CIRCLE_TAG}" != "" ]; then
              # Set Docker image tag
              DOCKER_IMAGE_TAG="${CIRCLE_TAG//v/}"
              DOCKER_IMAGE="openmf/ph-ee-bulk-processor:${DOCKER_IMAGE_TAG}"
              echo "Building Docker image: ${DOCKER_IMAGE}"

              # Build the Docker image
              ./gradlew bootJar
              docker build -t "${DOCKER_IMAGE}" .
 
              # Log in to Docker Hub
              echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin

              # Push the Docker image to Docker Hub
              docker push "${DOCKER_IMAGE}"
            else
              echo "Skipping Docker image build and push. This is not a tag release."
            fi

  build_and_push_latest_image:
    executor: docker-executor
    environment:
      JVM_OPTS: -Xmx512m
      TERM: dumb

    steps:
      - checkout
      # Install Docker to build and push the image
      - setup_remote_docker:
          version: 20.10.14

      # Build the Docker image
      - run:
          name: Build Docker image
          command: |
            ./gradlew bootJar
            docker build -t openmf/ph-ee-bulk-processor:latest .

      # Log in to DockerHub using environment variables
      - run:
          name: Login to DockerHub
          command: echo "${DOCKERHUB_PASSWORD}" | docker login -u "${DOCKERHUB_USERNAME}" --password-stdin

      # Push the Docker image to DockerHub
      - run:
          name: Push Docker image to DockerHub
          command: docker push openmf/ph-ee-bulk-processor:latest 

workflows:
  version: 2
  build_and_push:
    jobs:
      - build_push_tag_image:
          filters:
            tags:
              only: /^v\d+\.\d+\.\d+.*$/
          context:
            - DOCKER
      - build_and_push_latest_image:
          context:
              - DOCKER




